### ISSUE TITLE
Build error after upgrading node to 12.12.0 version

### ISSUE THREAD

**Issue by drav96** [nestjsx/nest-emitter#11]
Hello I get following error when builiding project

```
node_modules/nest-emitter/nest-emitter.module.d.ts:3:35 - error TS2694: Namespace 'NodeJS' has no exported member 'Events'.

declare type NestEmitter = NodeJS.Events;
```

**Comment by ahmedNY** [comment]
same here
